name: Karate Tests by Tag (On Demand)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select tag to execute'
        required: true
        type: choice
        options:
          - '@exitoso'
          - '@loginSuccess'
          - '@registroSucess'
          - '@registroFail'
          - '@loginFail'
          - '@registrarProducto'
          - '@InvalidToken'
          - '@CP07'
          - '@all'
        default: '@exitoso'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v6

      - name: Configurar Java Corretto 11 y Maven
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Descargar dependencias
        run: mvn dependency:resolve

      - name: Ejecutar pruebas Karate con TAG ${{ github.event.inputs.tag }}
        run: |
          if [ "${{ github.event.inputs.tag }}" == "@all" ]; then
            mvn clean test -Dtest=ConfigTest
          else
            mvn clean test -Dtest=ConfigTest -Dkarate.options="--tags ${{ github.event.inputs.tag }}"
          fi

      - name: Subir reporte de pruebas
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: karate-reports-${{ github.event.inputs.tag }}-${{ github.run_number }}
          path: target/karate-reports/
          retention-days: 30

      - name: Subir resumen en JSON
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: karate-summary-json-${{ github.event.inputs.tag }}
          path: target/karate-reports/karate-summary-json.txt